---

- name: Start | Container is started
  become_user: "{{ manage_container__start_items.value.hostuser }}"
  become: true
  ansible.builtin.systemd_service:
    name: "{{ manage_container__start_items.value.service_name }}"
    state: started
    scope: user
  loop: "{{ manage_container__config | dict2items }}"
  loop_control:
    loop_var: manage_container__start_items

- name: Start | Wait for Container to come up
  ansible.builtin.wait_for:
    port: "{{ manage_container__ports_items.value }}"
    delay: 5
    sleep: 1
    state: started
  loop: "{{ manage_container__ports }}"
  loop_control:
    loop_var: manage_container__ports_items
